// Generated by dia2code
#ifndef STATE__BOARDS__H
#define STATE__BOARDS__H


namespace state {

  /// class Boards - 
  class Boards {
    // Attributes
  private:
    int id;
    Monsters[] monsters;
    Spells[] spells;
    Traps[] traps;
    Cards[] graveyard;
    // Operations
  public:
    void attackPosition ();
    void defensePosition ();
    void addMonster ();
    void removeMonster ();
    void addSpell ();
    void removeSpell ();
    void addTrap ();
    void removeTrap ();
    void appel ();
    // Setters and Getters
  };

};

#endif
