// Generated by dia2code
#ifndef STATE__BOARDS__H
#define STATE__BOARDS__H

#include <string>
#include <vector>

namespace state {

  /// class Boards - 
  class Boards {
    // Attributes
  private:
    int id;
    vector<Monsters>  monsters;
    vector<Spells>  spells;
    vector<Traps>  traps;
    vector<Cards>  graveyard;
    // Operations
  public:
    void attackPosition ();
    void defensePosition ();
    void addMonster ();
    void removeMonster ();
    void addSpell ();
    void removeSpell ();
    void addTrap ();
    void removeTrap ();
    void appel ();
    // Setters and Getters
  };

};

#endif
