// Generated by dia2code
#ifndef STATE__CALCULATION__H
#define STATE__CALCULATION__H


namespace state {

  /// class Calculation - 
  class Calculation {
    // Attributes
  private:
    int  lifePointsPlayer1;
    int lifePointsPlayer2;
    int attackPointsPlayer1;
    int attackPointsPlayer2;
    int defensePointsPlayer1;
    int defensePointsPlayer2;
    // Operations
  public:
    int getDefensePointsPlayer1 ();
    int getDefensePointsPlayer2 ();
    int getAttackPointsPlayer1 ();
    int getAttackPointsPlayer2 ();
    int getLifePointsPlayer1 ();
    int getLifePointsPlayer2 ();
    // Setters and Getters
  };

};

#endif
