// Generated by dia2code
#ifndef STATE__CARDS__H
#define STATE__CARDS__H


namespace state {
  class CardTypes;
}

#include "CardTypes.h"

namespace state {

  /// class Cards - 
  class Cards {
    // Attributes
  protected:
    int idCard;
    string name;
    string description;
    CardTypes type;
    etat  state ;
    // Setters and Getters
    int getIdCard() const;
    void setIdCard(int idCard);
    const string& getName() const;
    void setName(const string& name);
    const string& getDescription() const;
    void setDescription(const string& description);
    const CardTypes& getType() const;
    void setType(const CardTypes& type);
    const etat & getState () const;
    void setState (const etat & state );
  };

};

#endif
