// Generated by dia2code
#ifndef STATE__CARDTYPES__H
#define STATE__CARDTYPES__H


namespace state {

  /// class CardTypes - 
  class CardTypes {
    // Attributes
  private:
    string type;
    // Operations
  public:
    void isMonster ();
    void isSpell ();
    void isTrap ();
    // Setters and Getters
  };

};

#endif
