// Generated by dia2code
#ifndef STATE__DECKS__H
#define STATE__DECKS__H

#include <vector>

namespace state {
  class Cards;
}

#include "Cards.h"

namespace state {

  /// class Decks - 
  class Decks {
    // Attributes
  private:
    int id;
    std::vector<Cards> cardsInDeck;
    std::vector<Cards> cardsInHand;
    int numberOfCards     = 40;
    // Operations
  public:
    Decks (std::vector<Cards> cardsInDeck, std::vector<Cards> cardsInHands);
    Decks ();
    void shuffle ();
    void drawCard ();
    void addCard ();
    void removeCard ();
    // Setters and Getters
  };

};

#endif
