// Generated by dia2code
#ifndef STATE__DECKS__H
#define STATE__DECKS__H


namespace state {

  /// class Decks - 
  class Decks {
    // Attributes
  private:
    int id;
    Cards[] cardsInDeck;
    Cards[] cardsInHand;
    int numberOfCards     = 40;
    // Operations
  public:
    void shuffle ();
    void drawCard ();
    void addCard ();
    void removeCard ();
    // Setters and Getters
  };

};

#endif
