// Generated by dia2code
#ifndef STATE__MONSTERS__H
#define STATE__MONSTERS__H


namespace state {

  /// class Monsters - 
  class Monsters {
    // Attributes
  public:
    int effet ;
  private:
    int level;
    int attack;
    int defense;
    bool position;
    // Operations
  public:
    void attack (carte c);
    void setSpell ();
    // Setters and Getters
  };

};

#endif
