// Generated by dia2code
#ifndef STATE__PLAYERS__H
#define STATE__PLAYERS__H


namespace state {
  class Decks;
  class Boards;
}

#include "GameStatus.h"
#include "Decks.h"
#include "Boards.h"

namespace state {

  /// class Players - 
  class Players {
    // Attributes
  private:
    int id;
    GameStatus status;
    Decks deck;
    Boards board;
    int lifepoints;
    // Operations
  public:
    void drawCard ();
    void placeCard ();
    void setSpell ();
    void endTurn ();
    void looseLifePoints (int degat );
    // Setters and Getters
  };

};

#endif
