// Generated by dia2code
#ifndef STATE__SPELLEFFECT__H
#define STATE__SPELLEFFECT__H


namespace state {

  enum spellEffect {
    Ritual,
    Normal,
    Continuous,
    Field ,
    Equiped ,
    Quickplay
  };

};

#endif
