// Generated by dia2code
#ifndef STATE__SPELLS__H
#define STATE__SPELLS__H


namespace state {

  /// class Spells - 
  class Spells {
    // Attributes
  private:
    string effect;
    // Operations
  public:
    bool isOn ();
    // Setters and Getters
  };

};

#endif
