// Generated by dia2code
#ifndef STATE__TRAPS__H
#define STATE__TRAPS__H


#include "trapEffect.h"

namespace state {

  /// class Traps - 
  class Traps {
    // Attributes
  private:
    trapEffect effect;
    // Operations
  public:
    void activate ();
    bool isOn ();
    // Setters and Getters
  };

};

#endif
